/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.views;

import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

import edu.uci.ics.jung.graph.Graph;

/**
 *
 * @author houk
 */
public class ParametersFrame extends javax.swing.JDialog {

    /**
     * Creates new form ParametersFrame
     */
    private String poid;
    private String omptimisation;
    private Graph globalGraph;
    private javax.swing.JDesktopPane jDesktopPane;
    private int dialogResult = JOptionPane.CANCEL_OPTION;
    
    public int getDialogResult()
	{
		return dialogResult;
	}

    public ParametersFrame(String poids, String omptimisations, Graph globalGRAPH, JDesktopPane jDesktopPANE) {
        poid = poids;
        omptimisation = omptimisations;
        globalGraph = globalGRAPH;

        initComponents();
        jDesktopPane = jDesktopPANE;
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parametresPanel = new javax.swing.JPanel();
        poidsLabel = new javax.swing.JLabel();
        optimisationLabel = new javax.swing.JLabel();
        poidsText = new javax.swing.JTextField();
        omptimisationText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        VisualiserButton = new javax.swing.JButton();
        AnnulerButton = new javax.swing.JButton();
        ValiderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clustering Parameters");

        parametresPanel.setPreferredSize(new java.awt.Dimension(245, 235));

        poidsLabel.setText(" Clustering Threshold");

        optimisationLabel.setText("Cluster Expansion Threshold");

        poidsText.setText(poid);

        omptimisationText.setText(omptimisation);

        javax.swing.GroupLayout parametresPanelLayout = new javax.swing.GroupLayout(parametresPanel);
        parametresPanel.setLayout(parametresPanelLayout);
        parametresPanelLayout.setHorizontalGroup(
            parametresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametresPanelLayout.createSequentialGroup()
                        .addComponent(optimisationLabel)
                        .addContainerGap(138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametresPanelLayout.createSequentialGroup()
                        .addGroup(parametresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(parametresPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(omptimisationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(parametresPanelLayout.createSequentialGroup()
                                .addComponent(poidsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(poidsText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        parametresPanelLayout.setVerticalGroup(
            parametresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poidsLabel)
                    .addComponent(poidsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(parametresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optimisationLabel)
                    .addComponent(omptimisationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        VisualiserButton.setText("Visualize the Resulting Graph");
        VisualiserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualiserButtonActionPerformed(evt);
            }
        });

        AnnulerButton.setText("Cancel");
        AnnulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButtonActionPerformed(evt);
            }
        });

        ValiderButton.setText("Save");
        ValiderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(VisualiserButton)
                .addGap(37, 37, 37)
                .addComponent(AnnulerButton)
                .addGap(29, 29, 29)
                .addComponent(ValiderButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValiderButton)
                    .addComponent(AnnulerButton)
                    .addComponent(VisualiserButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(parametresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parametresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_AnnulerButtonActionPerformed
    	dialogResult = JOptionPane.CANCEL_OPTION;
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerButtonActionPerformed

    private void ValiderButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_ValiderButtonActionPerformed
        percentageParametre = Double.parseDouble(poidsText.getText());
        optimisationParametre = Double.parseDouble(omptimisationText.getText());
        dialogResult = JOptionPane.OK_OPTION;
        this.setVisible(false);
    }//GEN-LAST:event_ValiderButtonActionPerformed

    private void VisualiserButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_VisualiserButtonActionPerformed
        try {
            FirstGraphVisualization firstframeInt = new FirstGraphVisualization(globalGraph, "Visualization of the Resulting Graph", false, null);
            firstframeInt.setVisible(true); //necessary as of 1.3
            jDesktopPane.add(firstframeInt);
            firstframeInt.setSelected(true);
        } catch (PropertyVetoException | IOException ex) {
            Logger.getLogger(ParametersFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VisualiserButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JButton ValiderButton;
    private javax.swing.JButton VisualiserButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField omptimisationText;
    private javax.swing.JLabel optimisationLabel;
    private javax.swing.JPanel parametresPanel;
    private javax.swing.JLabel poidsLabel;
    private javax.swing.JTextField poidsText;
    // End of variables declaration//GEN-END:variables
    public static double percentageParametre = 0.2;
    public static double optimisationParametre = 0.1;
}
