/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uvsq.adam.tiorg.views;

import fr.uvsq.adam.processings.FileToModelGraph;
import fr.uvsq.adam.processings.FromDirectedToUndirectedGraph;
import fr.uvsq.adam.search.ElementsManagment;
import edu.uci.ics.jung.graph.DirectedGraph;
import edu.uci.ics.jung.graph.DirectedSparseGraph;
import edu.uci.ics.jung.graph.Graph;
import edu.uci.ics.jung.graph.UndirectedSparseGraph;
import edu.uci.ics.jung.graph.util.EdgeType;
import fr.uvsq.adam.search.Ranking;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.RDFNode;
import org.apache.jena.rdf.model.Statement;
import org.jdom2.Element;

import javax.swing.*;
import java.awt.*;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import static fr.uvsq.adam.tiorg.TioRG.TIORG_APP;

/**
 *
 * @author houk
 */
public class KeywordsSearch2 extends javax.swing.JFrame {

	public static String TITLE = "Keywords Search";
	
	private String dirIndex;
    private String query;
    private final HashMap<String, Point> coordinate;
    private Element keywordsOptions;
    private final JDesktopPane pane;
    private static Map candidateQueries = new HashMap();

    /**
     * La fenetre permettant de saisir les mots clés
     * @param coordinates Les coordonnées des noeuds du graph
     * @param jDesktopPANE la fenetre principale 
     */
    public KeywordsSearch2(String dirIndex, HashMap<String, Point> coordinates, JDesktopPane jDesktopPANE, Element keyWordsOptions) {
    	this.dirIndex = dirIndex;
        coordinate = coordinates;
        pane = jDesktopPANE;
        keywordsOptions = keyWordsOptions;
        initComponents();
        this.validate();
        this.setVisible(true);
        setLocationRelativeTo(null);
        setTitle(TITLE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchWords = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(428, 155));

        jCheckBox1.setText("Match Case");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try 
                {
                	searchButtonActionPerformed(evt);
                } 
                catch (Exception ex) {
                    Logger.getLogger(KeywordsSearch2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jLabel1.setText("Keywords to Search");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchWords))
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(searchButton)))
                .addGap(21, 21, 21)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(searchWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox1)
                .addComponent(searchButton)
                .addComponent(jButton1))
                .addContainerGap(103, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
/**
 * Le bouton cancel
 * @param evt 
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

	/**
	 * Lancement de la recherche mots clés
	 * 
	 * @param evt
	 * @throws Exception
	 */
	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception
	{

		try
		{
			query = searchWords.getText();
			// séparation des mots de la requete par espace
			String[] keywords = query.split(" ");

			Graph<RDFNode,Statement> g = null;
			UndirectedSparseGraph<RDFNode,Statement> undirecteGraph;
			Model modelTosearch;
			ArrayList<Ranking.TupleResultScore> modelList = new ArrayList<>();
			
			JInternalFrame curFrame = TIORG_APP.getMainWindow().getDesktop().getSelectedFrame();
			// Récupération du graphe en cours
			if(curFrame.getName() != null)
			{
				if( curFrame.getName().equals(FirstGraphVisualization.NAME) 
					|| curFrame.getName().equals(ClustersVizualisation.NAME_THEME)
					)
					g = ((FirstGraphVisualization)curFrame).graph;
				else
				{
					if( curFrame.getName().equals(QueriesVizualisation.NAME) )
						g = ((QueriesVizualisation)curFrame).graph;
				}
			}
			if(g == null)
				return;
			
			if( !(g instanceof DirectedGraph) )
			{
				DirectedSparseGraph<RDFNode,Statement> graph = new DirectedSparseGraph<RDFNode,Statement>();
				for (Statement stat: g.getEdges())
		        {
					graph.addEdge(stat, stat.getSubject(), stat.getObject(), EdgeType.DIRECTED);
		        }
				g = graph;
			}
			
			modelTosearch = FileToModelGraph.GraphToModel(g);
			undirecteGraph = FromDirectedToUndirectedGraph.FromDirectedToUndirectedGraph(g);

			try
			{

				modelList = ElementsManagment.main(dirIndex, query, keywords, keywordsOptions,
						modelTosearch, g, undirecteGraph);
			}
			catch(IOException ex)
			{
				Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
			}

			this.dispose();
			int index = 0;
			candidateQueries.clear();
			for(Ranking.TupleResultScore model : modelList)
			{
				String result = "Result " + index;
				candidateQueries.put(result, model.getScore());
				index++;
			}

			QueriesVizualisation frameInt = new QueriesVizualisation(g, modelTosearch,
					undirecteGraph, coordinate, pane, TITLE + " : " + query, modelList);
			frameInt.setVisible(true);
			pane.add(frameInt);
			frameInt.setMaximum(true);
			frameInt.setSelected(true);
		}
		catch(PropertyVetoException | IOException ex)
		{
			Logger.getLogger(KeywordsSearch2.class.getName()).log(Level.SEVERE, null, ex);
		}
		// //--
		// try {
		// ElementsManagment.main(keywords);
		// } catch (Exception ex) {
		// Logger.getLogger(KeyWordsSearch.class.getProjectName()).log(Level.SEVERE, null, ex); }

	}
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchWords;
    // End of variables declaration
}
